version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.5.4

    steps:
      - checkout

      - run:
          name: Install build dependencies
          command: |
            apt-get update
            apt-get install -y --no-install-recommends --quiet build-essential

      - restore_cache:
          keys: conda

      - run:
          name: Install library
          command: |
            conda install python=3.6 numpy pip --yes --quiet
            pip install --progress-bar off -e .[test,ssm_gpy,ssm_pytorch]

      - save_cache:
          key: conda
          paths:
            - ~/.cache/pip
            - /opt/conda/pkgs

      - run:
          name: Run tests
          command: |
            bash scripts/test_code.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

